### ISSUE TITLE
Plugins: Allow passing objects

### ISSUE THREAD

**Issue by IngwiePhoenix** [SjonHortensius/LRTEditor#10]
Currently, `.forEach` is used to iterate over the plugins. But if the given plugin is, for instance, an object, there is no need to further search `window`. Also, allowing that pretty much let's one use self-made plugins a bit easier.

Background: I am using WebPack. Using the `exports-loader`, I can obtain the Editor although it is not CommonJS aware. But adding plugins would be reeeally tricky. :)

**Comment by SjonHortensius** [comment]
That's an excellent idea, I've implemented it. It's a lot cleaner to pass instances instead of 'magic' strings too
